### ISSUE TITLE
Use minimum_allowed_balance to determine liquidity for getQuote

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-connector#115] opened 2016-03-21 21:05 UTC
When the connector checks the balance in its account on a ledger ([here](https://github.com/interledger/five-bells-connector/blob/2ee1a6f11c73282f5950148a124392fe0d2f4ea8/src/models/quote.js#L129-L133)) it should take the `minimum_allowed_balance` field in case it is allowed to go negative

**Comment by michielbdejong** [comment] 2017-03-07 17:23
IIUC this is a duplicate of #247

**Closed by michielbdejong** 2017-03-07 17:23 UTC
